---
- name: Install Python and Docker
  hosts: all
  become: yes
  tasks:
    - name: Install Python on remote machine
      raw: |
        sudo apt update && sudo apt install -y python3

    - name: Install Python3 pip (if required for Ansible dependencies)
      raw: sudo apt install -y python3-pip

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Download Docker GPG key
      raw: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg


    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to the Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
        state: present